import * as THREE from "https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js";
import {createAvatar3D,poseAvatar3D,drawAvatar2D} from "./avatar.js";
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),clone=o=>JSON.parse(JSON.stringify(o));
function size(o){if(o.type==="ball")return{x:o.scale,y:o.scale,z:o.scale};if(o.type==="tree")return{x:1.5*o.scale,y:3*o.scale,z:1.5*o.scale};return{x:(o.sx||2)*o.scale,y:(o.sy||1)*o.scale,z:(o.sz||2)*o.scale}}
function meshFor(o){const g=new THREE.Group();g.userData.objectId=o.id;g.userData.sceneObject=o;const mat=new THREE.MeshStandardMaterial({color:o.color||"#696969",roughness:o.material==="metal"?0.35:.8,transparent:o.material==="glass",opacity:o.material==="glass"?.45:1,emissive:o.material==="neon"?new THREE.Color(o.color||"#00aaff"):0});
 if(o.type==="ball")g.add(new THREE.Mesh(new THREE.SphereGeometry(.5,20,12),mat));
 else if(o.type==="tree"){const t=new THREE.Mesh(new THREE.CylinderGeometry(.18,.25,1.5,8),new THREE.MeshStandardMaterial({color:"#6b4427"}));t.position.y=.75;g.add(t);const c=new THREE.Mesh(new THREE.SphereGeometry(.9,14,10),new THREE.MeshStandardMaterial({color:o.color||"#4d8b45"}));c.position.y=1.9;g.add(c)}
 else if(o.type==="spawn"){const r=new THREE.Mesh(new THREE.RingGeometry(.55,.7,32),new THREE.MeshBasicMaterial({color:0x35a7ff,side:THREE.DoubleSide}));r.rotation.x=-Math.PI/2;g.add(r)}
 else{const s=size(o),m=new THREE.Mesh(new THREE.BoxGeometry(s.x,s.y,s.z),mat);m.position.y=s.y/2;g.add(m)}
 g.position.set(o.x||0,o.y||0,o.z||0);g.rotation.y=o.ry||0;g.scale.setScalar(o.scale||1);return g}
export class ThreeEditor{
 constructor(canvas,data,onSelect,onChange){this.canvas=canvas;this.data=data;this.onSelect=onSelect;this.onChange=onChange;this.tool="select";this.selected=null;this.drag=false;this.last={x:0,y:0};this.renderer=new THREE.WebGLRenderer({canvas,antialias:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.5));this.renderer.setClearColor(0x8bc6ed);this.scene=new THREE.Scene();this.scene.fog=new THREE.Fog(0x8bc6ed,30,100);this.camera=new THREE.PerspectiveCamera(55,1,.1,300);this.camera.position.set(12,10,14);this.target=new THREE.Vector3();this.scene.add(new THREE.HemisphereLight(0xffffff,0x52606a,2));const sun=new THREE.DirectionalLight(0xffffff,2.2);sun.position.set(10,20,5);this.scene.add(sun);const grid=new THREE.GridHelper(80,80,0x9ba5ad,0xcbd2d7);grid.position.y=-.01;this.scene.add(grid);this.meshes=new Map();this.rebuild();this.bind();this.resize();this.loop()}
 rebuild(){for(const c of [...this.scene.children])if(c.userData.objectId)this.scene.remove(c);this.meshes.clear();for(const o of this.data.objects||[]){const m=meshFor(o);this.scene.add(m);this.meshes.set(o.id,m)}}
 bind(){this.canvas.addEventListener("pointerdown",e=>{this.canvas.setPointerCapture(e.pointerId);this.drag=true;this.last={x:e.clientX,y:e.clientY};const h=this.pick(e);if(h){this.selected=h.userData.objectId;this.onSelect(this.data.objects.find(o=>o.id===this.selected)||null)}});
 this.canvas.addEventListener("pointermove",e=>{if(!this.drag)return;const dx=e.clientX-this.last.x,dy=e.clientY-this.last.y;this.last={x:e.clientX,y:e.clientY};if(this.selected){const o=this.data.objects.find(x=>x.id===this.selected);if(!o)return;if(this.tool==="move"){const p=this.ground(e);if(p){o.x=p.x;o.z=p.z}}else if(this.tool==="rotate")o.ry=(o.ry||0)+dx*.01;else if(this.tool==="scale")o.scale=clamp((o.scale||1)+dx*.01,.2,8);this.apply(o);this.onChange(o)}else{this.target.x-=dx*.02;this.target.z+=dy*.02}});
 this.canvas.addEventListener("pointerup",()=>this.drag=false);this.canvas.addEventListener("wheel",e=>{e.preventDefault();this.camera.position.multiplyScalar(1+(e.deltaY>0?.06:-.06));this.camera.position.y=clamp(this.camera.position.y,2,80)},{passive:false})}
 setTool(t){this.tool=t}
 pick(e){const r=this.canvas.getBoundingClientRect(),v=new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),ray=new THREE.Raycaster();ray.setFromCamera(v,this.camera);for(const h of ray.intersectObjects([...this.meshes.values()].flatMap(g=>g.children),true)){let n=h.object;while(n&&!n.userData.objectId)n=n.parent;if(n)return n}return null}
 ground(e){const r=this.canvas.getBoundingClientRect(),v=new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),ray=new THREE.Raycaster();ray.setFromCamera(v,this.camera);return ray.ray.intersectPlane(new THREE.Plane(new THREE.Vector3(0,1,0),0),new THREE.Vector3())}
 apply(o){const m=this.meshes.get(o.id);if(m){m.position.set(o.x||0,o.y||0,o.z||0);m.rotation.y=o.ry||0;m.scale.setScalar(o.scale||1)}}
 add(o){this.data.objects.push(o);const m=meshFor(o);this.scene.add(m);this.meshes.set(o.id,m)}
 resize(){const w=this.canvas.clientWidth||600,h=this.canvas.clientHeight||400;this.renderer.setSize(w,h,false);this.camera.aspect=w/h;this.camera.updateProjectionMatrix()}
 loop(){requestAnimationFrame(()=>this.loop());this.camera.lookAt(this.target);this.renderer.render(this.scene,this.camera)}
}
export class ThreePlay{
 constructor(canvas,data,avatar,onExit,onStatus){this.canvas=canvas;this.data=clone(data);this.onExit=onExit;this.onStatus=onStatus;this.keys={};this.pos=new THREE.Vector3();this.vel=new THREE.Vector3();this.yaw=0;this.grounded=true;this.phase=0;this.running=true;this.renderer=new THREE.WebGLRenderer({canvas,antialias:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.5));this.renderer.setClearColor(0x78b7e5);this.scene=new THREE.Scene();this.scene.fog=new THREE.Fog(0x78b7e5,35,120);this.camera=new THREE.PerspectiveCamera(65,1,.1,300);this.scene.add(new THREE.HemisphereLight(0xffffff,0x4c5560,2));const sun=new THREE.DirectionalLight(0xffffff,2.5);sun.position.set(10,20,10);this.scene.add(sun);this.objects=[];for(const o of this.data.objects||[]){const m=meshFor(o);this.scene.add(m);this.objects.push({o,m,s:size(o)})}this.avatar=createAvatar3D(avatar||{},{});this.scene.add(this.avatar);this.bind();this.resize();this.last=performance.now();this.loop()}
 bind(){this.down=e=>{this.keys[e.key.toLowerCase()]=true;if(e.code==="Space")this.keys.space=true};this.up=e=>{this.keys[e.key.toLowerCase()]=false;if(e.code==="Space")this.keys.space=false};window.addEventListener("keydown",this.down);window.addEventListener("keyup",this.up);this.canvas.addEventListener("pointerdown",e=>{this.look=true;this.lastPointer={x:e.clientX,y:e.clientY};this.canvas.setPointerCapture(e.pointerId)});this.canvas.addEventListener("pointermove",e=>{if(this.look){this.yaw-=(e.clientX-this.lastPointer.x)*.006;this.lastPointer={x:e.clientX,y:e.clientY}}});this.canvas.addEventListener("pointerup",()=>this.look=false)}
 input(v){this.keys={...this.keys,...(v||{})}}
 collision(n){const r=.42;for(const q of this.objects){if(q.o.type==="spawn")continue;const o=q.o,s=q.s;if(Math.abs(n.x-(o.x||0))<s.x/2+r&&Math.abs(n.z-(o.z||0))<s.z/2+r&&n.y<=((o.y||0)+s.y)&&n.y+1.5>=(o.y||0))return{hit:true,top:(o.y||0)+s.y}}return{hit:false}}
 tick(dt){const f=(this.keys.w||this.keys.arrowup||this.keys.up?1:0)-(this.keys.s||this.keys.arrowdown||this.keys.down?1:0),s=(this.keys.d||this.keys.arrowright||this.keys.right?1:0)-(this.keys.a||this.keys.arrowleft||this.keys.left?1:0);const d=new THREE.Vector3(s,0,f);if(d.lengthSq())d.normalize().applyAxisAngle(new THREE.Vector3(0,1,0),this.yaw);this.vel.x=d.x*4.8;this.vel.z=d.z*4.8;if((this.keys.space||this.keys.jump)&&this.grounded){this.vel.y=6.5;this.grounded=false}this.vel.y-=16*dt;const n=this.pos.clone().addScaledVector(this.vel,dt);if(n.y<0){n.y=0;this.vel.y=0;this.grounded=true}const hit=this.collision(n);if(hit.hit&&this.vel.y<=0){n.y=hit.top;this.vel.y=0;this.grounded=true}this.pos.copy(n);this.avatar.position.copy(this.pos);this.avatar.rotation.y=this.yaw;this.phase+=dt;poseAvatar3D(this.avatar,this.phase,d.lengthSq()>0,!this.grounded);this.camera.position.lerp(new THREE.Vector3(this.pos.x-Math.sin(this.yaw)*7,this.pos.y+4,this.pos.z-Math.cos(this.yaw)*7),.12);this.camera.lookAt(this.pos.x,this.pos.y+1.1,this.pos.z);this.onStatus?.(d.lengthSq()?"PLAYING • JU avatar rig active":"READY • JU avatar rig active")}
 loop(){if(!this.running)return;requestAnimationFrame(()=>this.loop());const n=performance.now(),dt=Math.min(.033,(n-(this.last||n))/1000);this.last=n;this.tick(dt);this.renderer.render(this.scene,this.camera)}
 resize(){const w=this.canvas.clientWidth||600,h=this.canvas.clientHeight||400;this.renderer.setSize(w,h,false);this.camera.aspect=w/h;this.camera.updateProjectionMatrix()}
 stop(){this.running=false;window.removeEventListener("keydown",this.down);window.removeEventListener("keyup",this.up);this.renderer.dispose();this.onExit?.()}
}
export class TwoDPlay{
 constructor(canvas,data,avatar,onExit,onStatus){this.canvas=canvas;this.ctx=canvas.getContext("2d");this.data=clone(data);this.avatar=avatar;this.onExit=onExit;this.onStatus=onStatus;this.keys={};this.x=0;this.y=0;this.vy=0;this.cam=0;this.phase=0;this.grounded=false;this.running=true;this.bind();this.resize();this.last=performance.now();this.loop()}
 bind(){this.down=e=>{this.keys[e.key.toLowerCase()]=true;if(e.code==="Space")this.keys.space=true};this.up=e=>{this.keys[e.key.toLowerCase()]=false;if(e.code==="Space")this.keys.space=false};window.addEventListener("keydown",this.down);window.addEventListener("keyup",this.up)}
 input(v){this.keys={...this.keys,...(v||{})}}
 tick(dt){const l=this.keys.a||this.keys.arrowleft||this.keys.left,r=this.keys.d||this.keys.arrowright||this.keys.right;this.x+=(r-l)*4.2*dt;this.vy+=18*dt;if((this.keys.space||this.keys.jump)&&this.grounded){this.vy=-7;this.grounded=false}this.y+=this.vy*dt;let ground=0;for(const o of this.data.objects||[]){if(["platform","block","terrain"].includes(o.type)){const half=(o.sx||2)*o.scale/2;if(this.x>(o.x||0)-half&&this.x<(o.x||0)+half&&this.y>=(o.y||0)-2&&this.y<=(o.y||0)+1)ground=Math.max(ground,o.y||0)}}if(this.y>ground){this.y=ground;this.vy=0;this.grounded=true}this.cam+=(this.x-this.cam)*.1;this.phase+=dt}
 draw(){const d=devicePixelRatio||1,w=this.canvas.clientWidth||600,h=this.canvas.clientHeight||400;this.canvas.width=w*d;this.canvas.height=h*d;this.ctx.setTransform(d,0,0,d,0,0);this.ctx.fillStyle="#9fd4f3";this.ctx.fillRect(0,0,w,h);this.ctx.fillStyle="#8fc0dc";this.ctx.fillRect(0,h*.55,w,h*.45);const sx=w/2-this.cam*45,sy=h*.72;for(const o of this.data.objects||[]){const px=sx+(o.x||0)*45,py=sy-(o.y||0)*45,sc=o.scale||1;this.ctx.fillStyle=o.color||"#696969";if(o.type==="ball"){this.ctx.beginPath();this.ctx.arc(px,py-15*sc,15*sc,0,Math.PI*2);this.ctx.fill()}else if(o.type==="tree"){this.ctx.fillStyle="#6b4427";this.ctx.fillRect(px-5,py-70*sc,10,70*sc);this.ctx.fillStyle=o.color||"#4d8b45";this.ctx.beginPath();this.ctx.arc(px,py-80*sc,32*sc,0,Math.PI*2);this.ctx.fill()}else this.ctx.fillRect(px-(o.sx||2)*22*sc,py-(o.sy||1)*45*sc,(o.sx||2)*45*sc,(o.sy||1)*45*sc)}drawAvatar2D(this.ctx,w/2+(this.x-this.cam)*45,h*.72-this.y*45,1.1,this.avatar,this.phase,!!(this.keys.a||this.keys.d||this.keys.arrowleft||this.keys.arrowright));this.ctx.fillStyle="#1e2d3a";this.ctx.font="12px sans-serif";this.ctx.fillText("2D PLAY • JU"+(this.avatar?.rig||"7"),14,22)}
 loop(){if(!this.running)return;requestAnimationFrame(()=>this.loop());const n=performance.now(),dt=Math.min(.033,(n-(this.last||n))/1000);this.last=n;this.tick(dt);this.draw();this.onStatus?.("PLAYING • 2D JU avatar active")}
 resize(){this.canvas.width=(this.canvas.clientWidth||600)*devicePixelRatio;this.canvas.height=(this.canvas.clientHeight||400)*devicePixelRatio}
 stop(){this.running=false;window.removeEventListener("keydown",this.down);window.removeEventListener("keyup",this.up);this.onExit?.()}
}
